import type {
  Series, Episode, Idea, Script, ScriptBlock, Scene, Asset,
  SubtitleCue, SubtitlePreset, ProcessingJob, ReviewItem,
  DriveExport, Hook, ManualProductionLog, PublishingRecord,
  AnalyticsRecord, ActivityEvent, Character, VisualStyle, Notification,
} from "../types";

const gradients = [
  "from-violet-900 via-primary/40 to-bg",
  "from-blue-900 via-secondary/40 to-bg",
  "from-amber-900 via-amber/40 to-bg",
  "from-emerald-900 via-success/40 to-bg",
  "from-rose-900 via-error/40 to-bg",
  "from-indigo-900 via-primary/30 to-bg",
  "from-cyan-900 via-secondary/30 to-bg",
  "from-orange-900 via-amber/30 to-bg",
];

function grad(i: number) {
  return gradients[i % gradients.length];
}

export const mockSeries: Series[] = [
  {
    id: "ser_001",
    title: "The Last Light",
    genre: "Drama / Mystery",
    category: "Entertainment",
    description: "A city loses its last light source, and its people must find meaning in the dark.",
    status: "Active",
    seasonCount: 2,
    episodeCount: 8,
    progress: 68,
    coverGradient: grad(0),
    updatedAt: "2026-09-28",
    targetAudience: "Adults 25-40",
    tone: "Contemplative, melancholic with hope",
    language: "Burmese",
    subtitleLanguage: "Burmese",
    defaultDuration: "3:00",
    publishingPlatforms: ["TikTok", "YouTube Shorts", "Instagram Reels"],
    synopsis: "In a city where the last streetlight goes out, a young woman discovers an old letter that changes everything she believed about her family's past. Each episode peels back a layer of mystery hidden in the darkness.",
  },
  {
    id: "ser_002",
    title: "Echoes of Tomorrow",
    genre: "Sci-Fi / Drama",
    category: "Entertainment",
    description: "Voices from the future reach a young radio operator in present-day Yangon.",
    status: "Active",
    seasonCount: 1,
    episodeCount: 5,
    progress: 45,
    coverGradient: grad(1),
    updatedAt: "2026-09-25",
    targetAudience: "Adults 20-35",
    tone: "Mysterious, eerie, philosophical",
    language: "Burmese",
    subtitleLanguage: "Burmese",
    defaultDuration: "3:00",
    publishingPlatforms: ["TikTok", "YouTube Shorts"],
    synopsis: "A late-night radio operator begins receiving transmissions from a future that hasn't happened yet. Each message carries a warning, a question, or a truth about someone in her city.",
  },
  {
    id: "ser_003",
    title: "The Door at 3:17",
    genre: "Horror / Mystery",
    category: "Entertainment",
    description: "Every night at 3:17 AM, a door appears in a hallway that was empty during the day.",
    status: "In Development",
    seasonCount: 1,
    episodeCount: 3,
    progress: 30,
    coverGradient: grad(2),
    updatedAt: "2026-09-22",
    targetAudience: "Adults 25-45",
    tone: "Suspenseful, restrained horror",
    language: "Burmese",
    subtitleLanguage: "Burmese",
    defaultDuration: "2:45",
    publishingPlatforms: ["TikTok", "Instagram Reels"],
    synopsis: "An apartment building resident notices a door that only appears at 3:17 AM. Behind it, a different room every night — and each one holds something that was lost.",
  },
  {
    id: "ser_004",
    title: "Letters Never Sent",
    genre: "Drama / Romance",
    category: "Entertainment",
    description: "A postwoman reads letters she was never supposed to deliver.",
    status: "On Hold",
    seasonCount: 1,
    episodeCount: 4,
    progress: 20,
    coverGradient: grad(3),
    updatedAt: "2026-09-15",
    targetAudience: "Adults 25-40",
    tone: "Tender, bittersweet",
    language: "Burmese",
    subtitleLanguage: "Burmese",
    defaultDuration: "3:15",
    publishingPlatforms: ["TikTok", "YouTube Shorts", "Facebook Reels"],
    synopsis: "A postwoman discovers a bundle of unsent letters from decades past. Each one tells a love story left incomplete — and she begins to wonder about her own.",
  },
  {
    id: "ser_005",
    title: "A Small Story from the Rain",
    genre: "Slice of Life",
    category: "Vlog",
    description: "Quiet moments captured during Yangon's monsoon season.",
    status: "Active",
    seasonCount: 1,
    episodeCount: 6,
    progress: 50,
    coverGradient: grad(4),
    updatedAt: "2026-09-20",
    targetAudience: "All ages",
    tone: "Calm, reflective, warm",
    language: "Burmese",
    subtitleLanguage: "Burmese",
    defaultDuration: "2:30",
    publishingPlatforms: ["TikTok", "Instagram Reels"],
    synopsis: "Each episode captures a small human moment during the rainy season — a shared umbrella, a flooded street, a cup of tea with a stranger. Small stories, quietly told.",
  },
];

export const mockEpisodes: Episode[] = [
  {
    id: "ep_001",
    publicId: "nar_20261002_0001",
    number: 1,
    title: "The Message That Arrived Tomorrow",
    burmeseTitle: "မနက်ဖြန်ရောက်မယ့် သတင်းစက်ား",
    seriesId: "ser_001",
    seriesTitle: "The Last Light",
    seasonNumber: 1,
    category: "Entertainment",
    thumbnailGradient: grad(0),
    duration: "3:02",
    status: "Subtitle Review",
    currentStep: "Subtitles",
    progress: 65,
    subtitleState: "In Review",
    approvalState: "Pending Review",
    exportState: "Not Ready",
    updatedAt: "2026-10-01",
    logline: "A letter arrives dated tomorrow — and everything it predicts comes true by evening.",
    synopsis: "May discovers a letter in her grandmother's old trunk, postmarked for tomorrow's date. As the day unfolds, each prediction in the letter comes true with unsettling precision.",
    emotionalTone: "Mysterious, melancholic",
    targetDuration: "3:00",
    hook: "What if you received a letter from tomorrow?",
    cta: "Follow for the next letter.",
    contentWarnings: ["Mild suspense"],
    productionTime: "4h 32m",
    sceneCount: 6,
    hasVideo: true,
    hasTranscript: true,
    hasThumbnail: true,
    criticalIssues: 1,
    checklist: [
      { label: "Idea captured", done: true },
      { label: "Structure complete", done: true },
      { label: "Script complete", done: true },
      { label: "Scenes defined", done: true },
      { label: "Assets ready", done: true },
      { label: "Video rendered", done: true },
      { label: "Transcript ready", done: true },
      { label: "Burmese subtitles reviewed", done: false },
      { label: "Thumbnail selected", done: true },
      { label: "Human review complete", done: false },
      { label: "Approved", done: false },
      { label: "Drive export complete", done: false },
      { label: "Publishing metadata ready", done: false },
    ],
  },
  {
    id: "ep_002",
    publicId: "nar_20261002_0002",
    number: 2,
    title: "Three Minutes Before Sunrise",
    burmeseTitle: "နေထွက်ချိန်မတိုင်မီ သုံးမိနစ်",
    seriesId: "ser_001",
    seriesTitle: "The Last Light",
    seasonNumber: 1,
    category: "Entertainment",
    thumbnailGradient: grad(1),
    duration: "2:58",
    status: "Approved",
    currentStep: "Approval",
    progress: 90,
    subtitleState: "Approved",
    approvalState: "Approved",
    exportState: "Ready",
    updatedAt: "2026-09-30",
    logline: "In the three minutes before dawn, the city's last streetlight shares its final memory.",
    synopsis: "As the last functioning streetlight prepares to go dark, it reveals the memories it has witnessed over forty years — love, loss, and quiet courage.",
    emotionalTone: "Tender, nostalgic",
    targetDuration: "3:00",
    hook: "The last light in the city has a secret.",
    cta: "Share if you remember your last streetlight.",
    contentWarnings: [],
    productionTime: "3h 15m",
    sceneCount: 5,
    hasVideo: true,
    hasTranscript: true,
    hasThumbnail: true,
    criticalIssues: 0,
    checklist: [
      { label: "Idea captured", done: true },
      { label: "Structure complete", done: true },
      { label: "Script complete", done: true },
      { label: "Scenes defined", done: true },
      { label: "Assets ready", done: true },
      { label: "Video rendered", done: true },
      { label: "Transcript ready", done: true },
      { label: "Burmese subtitles reviewed", done: true },
      { label: "Thumbnail selected", done: true },
      { label: "Human review complete", done: true },
      { label: "Approved", done: true },
      { label: "Drive export complete", done: false },
      { label: "Publishing metadata ready", done: false },
    ],
  },
  {
    id: "ep_003",
    publicId: "nar_20261002_0003",
    number: 1,
    title: "The Voice Behind the Wall",
    burmeseTitle: "နံရံနောက်က အသံ",
    seriesId: "ser_002",
    seriesTitle: "Echoes of Tomorrow",
    seasonNumber: 1,
    category: "Entertainment",
    thumbnailGradient: grad(2),
    duration: "3:05",
    status: "Script Review",
    currentStep: "Script",
    progress: 35,
    subtitleState: "Not Started",
    approvalState: "Not Submitted",
    exportState: "Not Ready",
    updatedAt: "2026-09-28",
    logline: "A radio operator hears her own voice from tomorrow night.",
    synopsis: "During her late-night shift, a radio operator picks up a frequency that carries her own voice — from a broadcast that hasn't been made yet.",
    emotionalTone: "Eerie, suspenseful",
    targetDuration: "3:00",
    hook: "What would you do if you heard your own voice from tomorrow?",
    cta: "Would you listen? Comment below.",
    contentWarnings: ["Mild suspense"],
    productionTime: "2h 45m",
    sceneCount: 4,
    hasVideo: false,
    hasTranscript: false,
    hasThumbnail: false,
    criticalIssues: 0,
    checklist: [
      { label: "Idea captured", done: true },
      { label: "Structure complete", done: true },
      { label: "Script complete", done: false },
      { label: "Scenes defined", done: false },
      { label: "Assets ready", done: false },
      { label: "Video rendered", done: false },
      { label: "Transcript ready", done: false },
      { label: "Burmese subtitles reviewed", done: false },
      { label: "Thumbnail selected", done: false },
      { label: "Human review complete", done: false },
      { label: "Approved", done: false },
      { label: "Drive export complete", done: false },
      { label: "Publishing metadata ready", done: false },
    ],
  },
  {
    id: "ep_004",
    publicId: "nar_20261002_0004",
    number: 2,
    title: "A Photograph with No Face",
    burmeseTitle: "မျက်နှာမရှိတဲ့ ဓာတ်ပုံ",
    seriesId: "ser_003",
    seriesTitle: "The Door at 3:17",
    seasonNumber: 1,
    category: "Entertainment",
    thumbnailGradient: grad(3),
    duration: "2:47",
    status: "Processing",
    currentStep: "Processing",
    progress: 50,
    subtitleState: "Not Started",
    approvalState: "Not Submitted",
    exportState: "Not Ready",
    updatedAt: "2026-10-01",
    logline: "Behind the 3:17 door, a room filled with photographs — all missing faces.",
    synopsis: "When the door appears at 3:17 AM, our protagonist finds a room of photographs. Every person is faceless. Until one photo has her own face.",
    emotionalTone: "Suspenseful, eerie",
    targetDuration: "2:45",
    hook: "Every photo in the room had no face. Except one.",
    cta: "Follow to see what's behind the next door.",
    contentWarnings: ["Mild horror imagery"],
    productionTime: "5h 20m",
    sceneCount: 5,
    hasVideo: true,
    hasTranscript: false,
    hasThumbnail: false,
    criticalIssues: 0,
    checklist: [
      { label: "Idea captured", done: true },
      { label: "Structure complete", done: true },
      { label: "Script complete", done: true },
      { label: "Scenes defined", done: true },
      { label: "Assets ready", done: true },
      { label: "Video rendered", done: false },
      { label: "Transcript ready", done: false },
      { label: "Burmese subtitles reviewed", done: false },
      { label: "Thumbnail selected", done: false },
      { label: "Human review complete", done: false },
      { label: "Approved", done: false },
      { label: "Drive export complete", done: false },
      { label: "Publishing metadata ready", done: false },
    ],
  },
  {
    id: "ep_005",
    publicId: "nar_20261002_0005",
    number: 1,
    title: "The Empty Chair",
    burmeseTitle: "ဗလာခုံးတန်း",
    seriesId: "ser_004",
    seriesTitle: "Letters Never Sent",
    seasonNumber: 1,
    category: "Entertainment",
    thumbnailGradient: grad(4),
    duration: "3:12",
    status: "Exported",
    currentStep: "Output",
    progress: 100,
    subtitleState: "Approved",
    approvalState: "Approved",
    exportState: "Exported",
    updatedAt: "2026-09-26",
    logline: "A letter about an empty chair reaches the person who was supposed to sit in it.",
    synopsis: "A postwoman delivers a letter to a tea shop owner about a chair that has been empty for twenty years. The letter reveals why.",
    emotionalTone: "Bittersweet, tender",
    targetDuration: "3:00",
    hook: "The chair was empty for twenty years. Today, a letter explains why.",
    cta: "Who do you think about when you see an empty chair?",
    contentWarnings: [],
    productionTime: "3h 40m",
    sceneCount: 4,
    hasVideo: true,
    hasTranscript: true,
    hasThumbnail: true,
    criticalIssues: 0,
    checklist: [
      { label: "Idea captured", done: true },
      { label: "Structure complete", done: true },
      { label: "Script complete", done: true },
      { label: "Scenes defined", done: true },
      { label: "Assets ready", done: true },
      { label: "Video rendered", done: true },
      { label: "Transcript ready", done: true },
      { label: "Burmese subtitles reviewed", done: true },
      { label: "Thumbnail selected", done: true },
      { label: "Human review complete", done: true },
      { label: "Approved", done: true },
      { label: "Drive export complete", done: true },
      { label: "Publishing metadata ready", done: true },
    ],
  },
  {
    id: "ep_006",
    publicId: "nar_20261002_0006",
    number: 3,
    title: "The Voice That Called from Yesterday",
    burmeseTitle: "မနေ့က ခေါ်ခဲ့တဲ့ အသံ",
    seriesId: "ser_002",
    seriesTitle: "Echoes of Tomorrow",
    seasonNumber: 1,
    category: "Entertainment",
    thumbnailGradient: grad(5),
    duration: "3:00",
    status: "Assets Needed",
    currentStep: "Assets",
    progress: 25,
    subtitleState: "Not Started",
    approvalState: "Not Submitted",
    exportState: "Not Ready",
    updatedAt: "2026-09-27",
    logline: "A voicemail from yesterday asks a question that hasn't been asked yet.",
    synopsis: "A man checks his voicemail and finds a message from himself, dated yesterday, about something that hasn't happened yet.",
    emotionalTone: "Mysterious, introspective",
    targetDuration: "3:00",
    hook: "His own voice called him from yesterday.",
    cta: "What would you say to your past self?",
    contentWarnings: [],
    productionTime: "0m",
    sceneCount: 0,
    hasVideo: false,
    hasTranscript: false,
    hasThumbnail: false,
    criticalIssues: 0,
    checklist: [
      { label: "Idea captured", done: true },
      { label: "Structure complete", done: true },
      { label: "Script complete", done: true },
      { label: "Scenes defined", done: false },
      { label: "Assets ready", done: false },
      { label: "Video rendered", done: false },
      { label: "Transcript ready", done: false },
      { label: "Burmese subtitles reviewed", done: false },
      { label: "Thumbnail selected", done: false },
      { label: "Human review complete", done: false },
      { label: "Approved", done: false },
      { label: "Drive export complete", done: false },
      { label: "Publishing metadata ready", done: false },
    ],
  },
  {
    id: "ep_007",
    publicId: "nar_20261002_0007",
    number: 2,
    title: "Rain on a Stranger's Shoulder",
    burmeseTitle: "အForeigner ပခုံးပေါ်က မိုး",
    seriesId: "ser_005",
    seriesTitle: "A Small Story from the Rain",
    seasonNumber: 1,
    category: "Vlog",
    thumbnailGradient: grad(6),
    duration: "2:30",
    status: "Needs Approval",
    currentStep: "Review",
    progress: 80,
    subtitleState: "Reviewed",
    approvalState: "Pending Review",
    exportState: "Not Ready",
    updatedAt: "2026-10-02",
    logline: "Two strangers share one umbrella for twelve blocks. Neither says a word.",
    synopsis: "During a sudden downpour, a young woman shares her umbrella with a stranger. They walk twelve blocks in silence, and something shifts in both of them.",
    emotionalTone: "Warm, quiet, reflective",
    targetDuration: "2:30",
    hook: "Twelve blocks. One umbrella. No words.",
    cta: "Have you shared an umbrella with a stranger?",
    contentWarnings: [],
    productionTime: "2h 10m",
    sceneCount: 3,
    hasVideo: true,
    hasTranscript: true,
    hasThumbnail: true,
    criticalIssues: 0,
    checklist: [
      { label: "Idea captured", done: true },
      { label: "Structure complete", done: true },
      { label: "Script complete", done: true },
      { label: "Scenes defined", done: true },
      { label: "Assets ready", done: true },
      { label: "Video rendered", done: true },
      { label: "Transcript ready", done: true },
      { label: "Burmese subtitles reviewed", done: true },
      { label: "Thumbnail selected", done: true },
      { label: "Human review complete", done: true },
      { label: "Approved", done: false },
      { label: "Drive export complete", done: false },
      { label: "Publishing metadata ready", done: false },
    ],
  },
  {
    id: "ep_008",
    publicId: "nar_20261002_0008",
    number: 4,
    title: "The Last Phone Call",
    burmeseTitle: "နောက်ဆုံးဖုန်းခေါ်ဆိုမှု",
    seriesId: "ser_001",
    seriesTitle: "The Last Light",
    seasonNumber: 1,
    category: "Entertainment",
    thumbnailGradient: grad(7),
    duration: "3:05",
    status: "Idea",
    currentStep: "Idea",
    progress: 5,
    subtitleState: "Not Started",
    approvalState: "Not Submitted",
    exportState: "Not Ready",
    updatedAt: "2026-10-02",
    logline: "A phone rings in a dark apartment. The caller ID shows a number that no longer exists.",
    synopsis: "When the power goes out across the city, an old rotary phone starts ringing. The number on the screen hasn't existed for fifteen years.",
    emotionalTone: "Mysterious, eerie",
    targetDuration: "3:00",
    hook: "The phone rang. The number hadn't existed for fifteen years.",
    cta: "Who would you call in the dark?",
    contentWarnings: [],
    productionTime: "0m",
    sceneCount: 0,
    hasVideo: false,
    hasTranscript: false,
    hasThumbnail: false,
    criticalIssues: 0,
    checklist: [
      { label: "Idea captured", done: true },
      { label: "Structure complete", done: false },
      { label: "Script complete", done: false },
      { label: "Scenes defined", done: false },
      { label: "Assets ready", done: false },
      { label: "Video rendered", done: false },
      { label: "Transcript ready", done: false },
      { label: "Burmese subtitles reviewed", done: false },
      { label: "Thumbnail selected", done: false },
      { label: "Human review complete", done: false },
      { label: "Approved", done: false },
      { label: "Drive export complete", done: false },
      { label: "Publishing metadata ready", done: false },
    ],
  },
];

export const mockIdeas: Idea[] = [
  {
    id: "idea_001",
    title: "The Balcony That Watched the City",
    concept: "A balcony that has observed the same street for fifty years tells its story through small details.",
    category: "Entertainment",
    hookType: "Mystery",
    emotion: "Nostalgic",
    priority: "Medium",
    status: "Shortlisted",
    createdAt: "2026-09-29",
    reference: "Inspired by an old building on 37th Street",
    notes: "Could work as a standalone or a series. Consider personification angle.",
    convertedTarget: "",
  },
  {
    id: "idea_002",
    title: "What the Tea Shop Heard",
    concept: "Overheard conversations at a Yangon tea shop, woven into a single narrative.",
    category: "Documentary",
    hookType: "Personal Story",
    emotion: "Warm",
    priority: "High",
    status: "Developing",
    createdAt: "2026-09-27",
    reference: "Tea shop on Anawrahta Road",
    notes: "Needs character development. Could be a 5-episode series.",
    convertedTarget: "ser_005",
  },
  {
    id: "idea_003",
    title: "The Man Who Collected Silence",
    concept: "A man records moments of complete silence across the city. The final recording changes everything.",
    category: "Entertainment",
    hookType: "Mystery",
    emotion: "Intriguing",
    priority: "Medium",
    status: "Raw Idea",
    createdAt: "2026-10-01",
    reference: "",
    notes: "Explore the concept of silence as a character.",
    convertedTarget: "",
  },
  {
    id: "idea_004",
    title: "Why My Grandmother's Clock Stopped",
    concept: "A personal story about a clock that stopped at the exact moment of a family event.",
    category: "Vlog",
    hookType: "Personal Story",
    emotion: "Bittersweet",
    priority: "Low",
    status: "Raw Idea",
    createdAt: "2026-09-25",
    reference: "True family story",
    notes: "Personal vlog format. Needs visual planning.",
    convertedTarget: "",
  },
  {
    id: "idea_005",
    title: "The Sixth Passenger",
    concept: "A bus that always has five passengers picks up a sixth one who changes the route.",
    category: "Entertainment",
    hookType: "Cliffhanger",
    emotion: "Suspenseful",
    priority: "High",
    status: "Converted to Episode",
    createdAt: "2026-09-20",
    reference: "",
    notes: "Converted to episode nar_20261002_0008",
    convertedTarget: "ep_008",
  },
  {
    id: "idea_006",
    title: "Teaching with Tea: 3-Minute Lessons",
    concept: "Burmese language lessons explained through tea shop scenarios.",
    category: "Educational",
    hookType: "Question",
    emotion: "Curious",
    priority: "Medium",
    status: "Shortlisted",
    createdAt: "2026-09-22",
    reference: "",
    notes: "Could be a tutorial series. Test with 3 episodes first.",
    convertedTarget: "",
  },
];

export const mockScriptBlocks: ScriptBlock[] = [
  { id: "sb_001", type: "Scene Heading", content: "INT. GRANDMOTHER'S ATTIC — NIGHT", order: 0 },
  { id: "sb_002", type: "Action", content: "May opens an old trunk. Dust dances in the moonlight. She finds a yellowed envelope.", order: 1 },
  { id: "sb_003", type: "On-Screen Text", content: "နောက်နေ့ စာ", order: 2 },
  { id: "sb_004", type: "Voiceover", content: "မနက်ဖြန်ရောက်မယ့် စာတစ်စောင်က ဒီနေ့ပဲ ရောက်လာတယ်။", order: 3 },
  { id: "sb_005", type: "Dialogue", content: "MAY: This letter... it's dated tomorrow.", order: 4 },
  { id: "sb_006", type: "Camera Note", content: "Slow push-in on the letter. The date is clearly visible.", order: 5 },
  { id: "sb_007", type: "Action", content: "May reads the first line. Her expression shifts from curiosity to unease.", order: 6 },
  { id: "sb_008", type: "Sound/Music Note", content: "Low ambient drone. A single piano note when she reads the date.", order: 7 },
  { id: "sb_009", type: "Voiceover", content: "စာထဲမှာ ရေးထားတာက မနက်ဖြန်ဖြစ်မယ့် အရာတွေပါ။", order: 8 },
  { id: "sb_010", type: "Transition", content: "CUT TO: The next morning.", order: 9 },
  { id: "sb_011", type: "Scene Heading", content: "EXT. CITY STREET — DAWN", order: 10 },
  { id: "sb_012", type: "Action", content: "The city wakes. The first prediction from the letter comes true — a bird lands on a specific windowsill.", order: 11 },
  { id: "sb_013", type: "On-Screen Text", content: "ပထမဆုံး သတင်းစ", order: 12 },
  { id: "sb_014", type: "Voiceover", content: "စာထဲက ပထမဆုံး ဟောပြောချက်က မှန်ကန်သွားတယ်။", order: 13 },
  { id: "sb_015", type: "Dialogue", content: "MAY (whispering): It's real. All of it.", order: 14 },
  { id: "sb_016", type: "Sound/Music Note", content: "Tension builds. Ambient city sounds fade to silence.", order: 15 },
  { id: "sb_017", type: "Transition", content: "FADE TO BLACK.", order: 16 },
];

export const mockScript: Script = {
  id: "scr_001",
  episodeId: "ep_001",
  blocks: mockScriptBlocks,
  wordCount: 245,
  estimatedDuration: "2:58",
  language: "Burmese / English",
  emotionalTone: "Mysterious, melancholic",
  hookStrength: "Strong",
  cta: "Follow for the next letter.",
  version: "v3.2",
  lastEdited: "2026-09-30",
  sourceType: "Human Edited",
};

export const mockScenes: Scene[] = [
  {
    id: "sc_001", episodeId: "ep_001", number: 1, title: "The Attic Discovery",
    durationTarget: "0:35", location: "Grandmother's Attic",
    characters: ["May"], visualDirection: "Moonlit, dusty, warm amber tones",
    voiceoverSummary: "May finds a letter postmarked for tomorrow.",
    requiredAssets: ["Attic background", "Old trunk prop", "Yellowed letter"],
    status: "Complete", warning: null, gradient: grad(0),
  },
  {
    id: "sc_002", episodeId: "ep_001", number: 2, title: "Reading the Letter",
    durationTarget: "0:45", location: "Attic",
    characters: ["May"], visualDirection: "Close-up on hands and face",
    voiceoverSummary: "The first prediction is read aloud.",
    requiredAssets: ["Letter close-up", "Burmese subtitle overlay"],
    status: "Complete", warning: null, gradient: grad(1),
  },
  {
    id: "sc_003", episodeId: "ep_001", number: 3, title: "Morning Comes",
    durationTarget: "0:40", location: "City Street — Dawn",
    characters: ["May"], visualDirection: "Cool blue dawn light, wide city shot",
    voiceoverSummary: "The first prediction comes true.",
    requiredAssets: ["City dawn background", "Bird animation"],
    status: "Ready", warning: null, gradient: grad(2),
  },
  {
    id: "sc_004", episodeId: "ep_001", number: 4, title: "The Second Prediction",
    durationTarget: "0:50", location: "Tea Shop",
    characters: ["May", "Tea Shop Owner"], visualDirection: "Warm interior, steam, crowded",
    voiceoverSummary: "May witnesses the second prediction at a tea shop.",
    requiredAssets: ["Tea shop interior", "Tea cup prop"],
    status: "Ready", warning: "Missing asset: Tea shop interior reference", gradient: grad(3),
  },
  {
    id: "sc_005", episodeId: "ep_001", number: 5, title: "The Final Line",
    durationTarget: "0:30", location: "Rooftop",
    characters: ["May"], visualDirection: "Golden hour, wide shot, city below",
    voiceoverSummary: "May reads the last line of the letter.",
    requiredAssets: ["Rooftop background", "Golden hour lighting"],
    status: "Draft", warning: "Duration may exceed target", gradient: grad(4),
  },
  {
    id: "sc_006", episodeId: "ep_001", number: 6, title: "Fade to Black",
    durationTarget: "0:08", location: "Black screen",
    characters: [], visualDirection: "Pure black with text overlay",
    voiceoverSummary: "End card with hook for next episode.",
    requiredAssets: ["End card graphic"],
    status: "Complete", warning: null, gradient: grad(5),
  },
];

export const mockAssets: Asset[] = [
  { id: "ast_001", name: "attic_bg_v2.png", type: "Image", duration: "—", dimensions: "1080×1920", fileSize: "2.4 MB", episodeId: "ep_001", episodeTitle: "The Message That Arrived Tomorrow", sceneId: "sc_001", version: "v2", isFinal: true, copyrightStatus: "Original", updatedAt: "2026-09-28", gradient: grad(0) },
  { id: "ast_002", name: "letter_closeup.png", type: "Image", duration: "—", dimensions: "1080×1920", fileSize: "1.8 MB", episodeId: "ep_001", episodeTitle: "The Message That Arrived Tomorrow", sceneId: "sc_002", version: "v1", isFinal: true, copyrightStatus: "Original", updatedAt: "2026-09-27", gradient: grad(1) },
  { id: "ast_003", name: "city_dawn_wide.png", type: "Image", duration: "—", dimensions: "1920×1080", fileSize: "3.2 MB", episodeId: "ep_001", episodeTitle: "The Message That Arrived Tomorrow", sceneId: "sc_003", version: "v1", isFinal: false, copyrightStatus: "Licensed", updatedAt: "2026-09-26", gradient: grad(2) },
  { id: "ast_004", name: "vo_may_narration.mp3", type: "Voiceover", duration: "2:45", dimensions: "—", fileSize: "8.1 MB", episodeId: "ep_001", episodeTitle: "The Message That Arrived Tomorrow", sceneId: "", version: "v3", isFinal: true, copyrightStatus: "Original", updatedAt: "2026-09-29", gradient: grad(3) },
  { id: "ast_005", name: "ambient_drone.wav", type: "Music", duration: "3:02", dimensions: "—", fileSize: "12.4 MB", episodeId: "ep_001", episodeTitle: "The Message That Arrived Tomorrow", sceneId: "", version: "v1", isFinal: true, copyrightStatus: "Licensed", updatedAt: "2026-09-25", gradient: grad(4) },
  { id: "ast_006", name: "ep001_video_v4.mp4", type: "Video", duration: "3:02", dimensions: "1080×1920", fileSize: "48.2 MB", episodeId: "ep_001", episodeTitle: "The Message That Arrived Tomorrow", sceneId: "", version: "v4", isFinal: false, copyrightStatus: "Original", updatedAt: "2026-09-30", gradient: grad(5) },
  { id: "ast_007", name: "thumbnail_golden_hour.png", type: "Thumbnail", duration: "—", dimensions: "1080×1920", fileSize: "1.2 MB", episodeId: "ep_001", episodeTitle: "The Message That Arrived Tomorrow", sceneId: "sc_005", version: "v1", isFinal: true, copyrightStatus: "Original", updatedAt: "2026-09-30", gradient: grad(6) },
  { id: "ast_008", name: "tea_shop_ref.jpg", type: "Reference", duration: "—", dimensions: "4032×3024", fileSize: "5.6 MB", episodeId: "ep_001", episodeTitle: "The Message That Arrived Tomorrow", sceneId: "sc_004", version: "v1", isFinal: false, copyrightStatus: "Reference Only", updatedAt: "2026-09-24", gradient: grad(7) },
  { id: "ast_009", name: "rooftop_bg_v1.png", type: "Image", duration: "—", dimensions: "1080×1920", fileSize: "2.9 MB", episodeId: "ep_001", episodeTitle: "The Message That Arrived Tomorrow", sceneId: "sc_005", version: "v1", isFinal: false, copyrightStatus: "Original", updatedAt: "2026-09-23", gradient: grad(0) },
  { id: "ast_010", name: "ep002_video_final.mp4", type: "Video", duration: "2:58", dimensions: "1080×1920", fileSize: "45.8 MB", episodeId: "ep_002", episodeTitle: "Three Minutes Before Sunrise", sceneId: "", version: "v5", isFinal: true, copyrightStatus: "Original", updatedAt: "2026-09-29", gradient: grad(1) },
  { id: "ast_011", name: "ep005_video_final.mp4", type: "Video", duration: "3:12", dimensions: "1080×1920", fileSize: "52.1 MB", episodeId: "ep_005", episodeTitle: "The Empty Chair", sceneId: "", version: "v3", isFinal: true, copyrightStatus: "Original", updatedAt: "2026-09-26", gradient: grad(2) },
  { id: "ast_012", name: "vo_narrator_old_man.mp3", type: "Voiceover", duration: "3:12", dimensions: "—", fileSize: "9.2 MB", episodeId: "ep_005", episodeTitle: "The Empty Chair", sceneId: "", version: "v2", isFinal: true, copyrightStatus: "Original", updatedAt: "2026-09-25", gradient: grad(3) },
];

export const mockSubtitleCues: SubtitleCue[] = [
  { id: "cue_001", number: 1, start: "0:00", end: "0:04", duration: "4s", originalText: "A letter arrives dated tomorrow.", burmeseText: "မနက်ဖြန်ရောက်မယ့် စာတစ်စောင်က ဒီနေ့ပဲ ရောက်လာတယ်။", sourceType: "Approved", reviewStatus: "Approved", issue: null, issueType: null, severity: null, reviewerNote: "" },
  { id: "cue_002", number: 2, start: "0:05", end: "0:09", duration: "4s", originalText: "It was in my grandmother's old trunk.", burmeseText: "အဘွားကြီးရဲ့ အနောက်ကျပ်သေတ္တာထဲမှာ ရှိနေခဲ့တယ်။", sourceType: "Human Edited", reviewStatus: "Reviewed", issue: null, issueType: null, severity: null, reviewerNote: "" },
  { id: "cue_003", number: 3, start: "0:10", end: "0:12", duration: "2s", originalText: "The date was clear.", burmeseText: "နေ့စွဲက ထင်ထင်ရှားရှား ရှိနေတယ်။", sourceType: "Machine Generated", reviewStatus: "Pending", issue: "Appears too briefly", issueType: "Appears too briefly", severity: "Needs Review", reviewerNote: "" },
  { id: "cue_004", number: 4, start: "0:13", end: "0:18", duration: "5s", originalText: "Every prediction in the letter came true by evening.", burmeseText: "စာထဲက ဟောပြောချက်တိုင်းက ညခင်းအတွင်း မှန်ကန်သွားတယ်။", sourceType: "Human Edited", reviewStatus: "Reviewed", issue: null, issueType: null, severity: null, reviewerNote: "" },
  { id: "cue_005", number: 5, start: "0:19", end: "0:27", duration: "8s", originalText: "The first sign was a bird that landed on a windowsill no one had noticed before. Then came the tea shop. Then the phone call that never should have happened.", burmeseText: "ပထမဆုံး လက္ခဏာက ဘယ်သူမှ သတိမထားမိခဲ့တဲ့ ပြတင်းပေါက်ပေါ် ငှက်တစ်ကောင် ဆင်းသက်တာပါပဲ။ နောက်ပြီးတော့ လက်ဖက်ရည်ဆိုင်။ ဒါနောက် ဖြစ်သင့်တဲ့ ဖုန်းခေါ်ဆိုမှု။", sourceType: "Machine Generated", reviewStatus: "Pending", issue: "Subtitle too long", issueType: "Subtitle too long", severity: "Critical", reviewerNote: "" },
  { id: "cue_006", number: 6, start: "0:25", end: "0:27", duration: "2s", originalText: "It was real.", burmeseText: "ဒါက တကယ်ပါ။", sourceType: "Machine Generated", reviewStatus: "Pending", issue: "Caption overlap with cue 5", issueType: "Caption overlap", severity: "Critical", reviewerNote: "" },
  { id: "cue_007", number: 7, start: "0:28", end: "0:33", duration: "5s", originalText: "By the time the last line came true, I understood.", burmeseText: "နောက်ဆုံးစာကြောင်း မှန်ကန်သွားတဲ့အခါ ကျွန်တော့်ကို နားလည်သွားတယ်။", sourceType: "Human Edited", reviewStatus: "Pending", issue: "Potential spelling issue", issueType: "Potential spelling issue", severity: "Needs Review", reviewerNote: "" },
  { id: "cue_008", number: 8, start: "0:34", end: "0:39", duration: "5s", originalText: "The letter wasn't from tomorrow. It was from yesterday.", burmeseText: "စာက မနက်ဖြန်က မဟုတ်ဘူး။ မနေ့က ဖြစ်နေတယ်။", sourceType: "Original", reviewStatus: "Approved", issue: null, issueType: null, severity: null, reviewerNote: "" },
  { id: "cue_009", number: 9, start: "0:40", end: "0:45", duration: "5s", originalText: "And it was meant for someone else.", burmeseText: "အဲဒါက တခြားသူအတွက် ဖြစ်နေတယ်။", sourceType: "Approved", reviewStatus: "Approved", issue: null, issueType: null, severity: null, reviewerNote: "" },
  { id: "cue_010", number: 10, start: "0:46", end: "0:52", duration: "6s", originalText: "Follow to read the next letter.", burmeseText: "နောက်စာအတွက် စောင့်ကြည့်ပါ။", sourceType: "Original", reviewStatus: "Pending", issue: "Punctuation issue: missing period", issueType: "Punctuation issue", severity: "Info", reviewerNote: "" },
];

export const mockPresets: SubtitlePreset[] = [
  { id: "ps_001", name: "Cinematic White", font: "Inter", fontSize: "24px", color: "#F7F5FA", background: "rgba(0,0,0,0.6)", outline: "1px #000", position: "Bottom Center", maxCharsPerLine: 32, maxLines: 2, minDisplayTime: "1.5s", maxDisplayTime: "6s", isDefault: true, previewGradient: grad(0) },
  { id: "ps_002", name: "Bold Yellow Hook", font: "Inter", fontSize: "28px", color: "#F1B75B", background: "rgba(0,0,0,0.7)", outline: "2px #000", position: "Top Center", maxCharsPerLine: 28, maxLines: 2, minDisplayTime: "2s", maxDisplayTime: "5s", isDefault: false, previewGradient: grad(1) },
  { id: "ps_003", name: "Dark Story", font: "Inter", fontSize: "22px", color: "#B5B2C2", background: "rgba(9,10,18,0.8)", outline: "None", position: "Bottom Center", maxCharsPerLine: 35, maxLines: 3, minDisplayTime: "2s", maxDisplayTime: "7s", isDefault: false, previewGradient: grad(2) },
  { id: "ps_004", name: "Educational Clean", font: "Inter", fontSize: "26px", color: "#F7F5FA", background: "rgba(75,199,232,0.15)", outline: "1px #4BC7E8", position: "Bottom Center", maxCharsPerLine: 30, maxLines: 2, minDisplayTime: "2s", maxDisplayTime: "6s", isDefault: false, previewGradient: grad(3) },
];

export const mockJobs: ProcessingJob[] = [
  { id: "job_001", jobId: "job_20261002_001", episodeId: "ep_001", episodeTitle: "The Message That Arrived Tomorrow", type: "Subtitle Generation", status: "Completed", progress: 100, started: "2026-09-30 14:22", duration: "3m 12s", retryCount: 0, errorMessage: null, input: "ep001_video_v4.mp4", output: "subtitles_ep001.srt" },
  { id: "job_002", jobId: "job_20261002_002", episodeId: "ep_001", episodeTitle: "The Message That Arrived Tomorrow", type: "Transcription", status: "Completed", progress: 100, started: "2026-09-30 14:15", duration: "5m 48s", retryCount: 0, errorMessage: null, input: "vo_may_narration.mp3", output: "transcript_ep001.txt" },
  { id: "job_003", jobId: "job_20261002_003", episodeId: "ep_004", episodeTitle: "A Photograph with No Face", type: "Video Render", status: "Processing", progress: 42, started: "2026-10-01 09:30", duration: "—", retryCount: 0, errorMessage: null, input: "project_ep004.json", output: "ep004_video_v1.mp4" },
  { id: "job_004", jobId: "job_20261002_004", episodeId: "ep_004", episodeTitle: "A Photograph with No Face", type: "Audio Extraction", status: "Completed", progress: 100, started: "2026-10-01 09:15", duration: "1m 22s", retryCount: 0, errorMessage: null, input: "raw_ep004.mp4", output: "audio_ep004.wav" },
  { id: "job_005", jobId: "job_20261002_005", episodeId: "ep_002", episodeTitle: "Three Minutes Before Sunrise", type: "Thumbnail Generation", status: "Completed", progress: 100, started: "2026-09-29 16:40", duration: "0m 45s", retryCount: 0, errorMessage: null, input: "ep002_video_final.mp4", output: "thumbnail_ep002.png" },
  { id: "job_006", jobId: "job_20261002_006", episodeId: "ep_005", episodeTitle: "The Empty Chair", type: "Drive Export", status: "Completed", progress: 100, started: "2026-09-26 11:00", duration: "2m 30s", retryCount: 0, errorMessage: null, input: "ep005_export_pack", output: "narrativ-forge/2026-09-26/nar_20261002_0005/" },
  { id: "job_007", jobId: "job_20261002_007", episodeId: "ep_006", episodeTitle: "The Voice That Called from Yesterday", type: "Timestamp Alignment", status: "Failed", progress: 0, started: "2026-09-27 13:10", duration: "0m 08s", retryCount: 2, errorMessage: "Audio file format not supported. Expected WAV, got M4A.", input: "vo_ep006.m4a", output: "aligned_ep006.srt" },
  { id: "job_008", jobId: "job_20261002_008", episodeId: "ep_007", episodeTitle: "Rain on a Stranger's Shoulder", type: "Subtitle Generation", status: "Queued", progress: 0, started: "—", duration: "—", retryCount: 0, errorMessage: null, input: "ep007_video_v1.mp4", output: "subtitles_ep007.srt" },
];

export const mockReviewItems: ReviewItem[] = [
  { id: "rev_001", episodeId: "ep_001", episodeTitle: "The Message That Arrived Tomorrow", seriesTitle: "The Last Light", reviewType: "Subtitle Review", priority: "High", issueCount: 4, criticalIssues: 2, dueDate: "2026-10-02", publicId: "nar_20261002_0001", thumbnailGradient: grad(0) },
  { id: "rev_002", episodeId: "ep_007", episodeTitle: "Rain on a Stranger's Shoulder", seriesTitle: "A Small Story from the Rain", reviewType: "Final Approval", priority: "Medium", issueCount: 0, criticalIssues: 0, dueDate: "2026-10-03", publicId: "nar_20261002_0007", thumbnailGradient: grad(1) },
  { id: "rev_003", episodeId: "ep_004", episodeTitle: "A Photograph with No Face", seriesTitle: "The Door at 3:17", reviewType: "Visual Review", priority: "Urgent", issueCount: 3, criticalIssues: 1, dueDate: "2026-10-02", publicId: "nar_20261002_0004", thumbnailGradient: grad(2) },
  { id: "rev_004", episodeId: "ep_002", episodeTitle: "Three Minutes Before Sunrise", seriesTitle: "The Last Light", reviewType: "Final Approval", priority: "High", issueCount: 0, criticalIssues: 0, dueDate: "2026-10-01", publicId: "nar_20261002_0002", thumbnailGradient: grad(3) },
];

export const mockDriveExports: DriveExport[] = [
  {
    id: "exp_001", episodeId: "ep_005", episodeTitle: "The Empty Chair",
    publicId: "nar_20261002_0005", status: "Exported", progress: 100,
    exportDate: "2026-09-26", fileCount: 8, driveFolderId: "mock_drive_folder_a1b2c3d4",
    dateFolder: "2026-09-26",
    requiredFiles: [
      { name: "video.mp4", present: true },
      { name: "subtitles.srt", present: true },
      { name: "subtitles.vtt", present: true },
      { name: "transcript.txt", present: true },
      { name: "script.md", present: true },
      { name: "metadata.json", present: true },
      { name: "thumbnail.jpg", present: true },
    ],
  },
  {
    id: "exp_002", episodeId: "ep_002", episodeTitle: "Three Minutes Before Sunrise",
    publicId: "nar_20261002_0002", status: "Ready", progress: 0,
    exportDate: "—", fileCount: 7, driveFolderId: "",
    dateFolder: "2026-10-02",
    requiredFiles: [
      { name: "video.mp4", present: true },
      { name: "subtitles.srt", present: true },
      { name: "subtitles.vtt", present: true },
      { name: "transcript.txt", present: true },
      { name: "script.md", present: true },
      { name: "metadata.json", present: true },
      { name: "thumbnail.jpg", present: true },
    ],
  },
  {
    id: "exp_003", episodeId: "ep_001", episodeTitle: "The Message That Arrived Tomorrow",
    publicId: "nar_20261002_0001", status: "Not Ready", progress: 0,
    exportDate: "—", fileCount: 0, driveFolderId: "",
    dateFolder: "2026-10-02",
    requiredFiles: [
      { name: "video.mp4", present: true },
      { name: "subtitles.srt", present: true },
      { name: "subtitles.vtt", present: false },
      { name: "transcript.txt", present: true },
      { name: "script.md", present: true },
      { name: "metadata.json", present: false },
      { name: "thumbnail.jpg", present: true },
    ],
  },
];

export const mockHooks: Hook[] = [
  { id: "hk_001", text: "What if you received a letter from tomorrow?", type: "Question", topic: "Mystery", emotion: "Intriguing", usageCount: 12, averageViews: 45000, completionRate: 78, shares: 340, performanceScore: 92, isDefault: false, isRecommended: true },
  { id: "hk_002", text: "Every photo in the room had no face. Except one.", type: "Mystery", topic: "Horror", emotion: "Suspenseful", usageCount: 8, averageViews: 52000, completionRate: 82, shares: 510, performanceScore: 95, isDefault: true, isRecommended: false },
  { id: "hk_003", text: "The chair was empty for twenty years. Today, a letter explains why.", type: "Personal Story", topic: "Drama", emotion: "Bittersweet", usageCount: 15, averageViews: 38000, completionRate: 71, shares: 280, performanceScore: 84, isDefault: false, isRecommended: false },
  { id: "hk_004", text: "His own voice called him from yesterday.", type: "Cliffhanger", topic: "Sci-Fi", emotion: "Eerie", usageCount: 6, averageViews: 41000, completionRate: 85, shares: 420, performanceScore: 88, isDefault: false, isRecommended: true },
  { id: "hk_005", text: "Twelve blocks. One umbrella. No words.", type: "Personal Story", topic: "Slice of Life", emotion: "Warm", usageCount: 4, averageViews: 28000, completionRate: 68, shares: 190, performanceScore: 72, isDefault: false, isRecommended: false },
  { id: "hk_006", text: "The door only appears at 3:17 AM. Don't open it.", type: "Warning", topic: "Horror", emotion: "Fearful", usageCount: 10, averageViews: 48000, completionRate: 80, shares: 460, performanceScore: 90, isDefault: false, isRecommended: false },
  { id: "hk_007", text: "You've been hearing this sound your whole life. You just never noticed.", type: "Question", topic: "Mystery", emotion: "Curious", usageCount: 3, averageViews: 22000, completionRate: 65, shares: 120, performanceScore: 61, isDefault: false, isRecommended: false },
];

export const mockManualLogs: ManualProductionLog[] = [
  { id: "log_001", videoId: "nar_20260915_0001", topic: "The Empty Tea Cup", hook: "She poured tea for someone who wasn't there.", hookType: "Mystery", category: "Entertainment", duration: "2:45", sceneCount: 4, toolsUsed: ["Manual editing", "Stock audio"], subtitleStyle: "Cinematic White", productionTime: "5h 30m", published: true, views: 42000, completionRate: 74, shares: 310, saves: 180, notes: "First manual video. Learned pacing is critical.", qualityScore: 7, platform: "TikTok", manualErrors: "Audio sync drift at 1:20", scriptLength: "320 words", voiceTool: "Manual recording", imageTool: "Manual photography", videoTool: "Manual editing" },
  { id: "log_002", videoId: "nar_20260918_0002", topic: "The Last Bus Home", hook: "The last bus of the night has one extra passenger.", hookType: "Cliffhanger", category: "Entertainment", duration: "3:00", sceneCount: 5, toolsUsed: ["Manual editing", "AI image gen", "Stock music"], subtitleStyle: "Bold Yellow Hook", productionTime: "4h 15m", published: true, views: 58000, completionRate: 81, shares: 520, saves: 340, notes: "Better hook performance. Cliffhanger works well.", qualityScore: 8, platform: "TikTok", manualErrors: "Subtitle timing off in scene 3", scriptLength: "280 words", voiceTool: "Manual recording", imageTool: "AI image generation", videoTool: "Manual editing" },
  { id: "log_003", videoId: "nar_20260922_0003", topic: "Rain and a Stranger's Book", hook: "She lent her book to a stranger in the rain. It came back annotated.", hookType: "Personal Story", category: "Vlog", duration: "2:30", sceneCount: 3, toolsUsed: ["Manual editing", "Stock audio"], subtitleStyle: "Dark Story", productionTime: "3h 45m", published: true, views: 31000, completionRate: 69, shares: 210, saves: 150, notes: "Personal story format performs well with subtitles.", qualityScore: 7, platform: "Instagram Reels", manualErrors: "Music too loud in intro", scriptLength: "250 words", voiceTool: "Manual recording", imageTool: "Manual photography", videoTool: "Manual editing" },
  { id: "log_004", videoId: "nar_20260925_0004", topic: "The Clock That Stopped at 3:17", hook: "The clock stopped at 3:17. The same time everything changed.", hookType: "Mystery", category: "Entertainment", duration: "3:05", sceneCount: 5, toolsUsed: ["AI image gen", "AI voice", "Manual editing"], subtitleStyle: "Cinematic White", productionTime: "3h 20m", published: true, views: 67000, completionRate: 83, shares: 680, saves: 420, notes: "AI-assisted saved ~2 hours vs fully manual.", qualityScore: 9, platform: "TikTok", manualErrors: "None significant", scriptLength: "295 words", voiceTool: "AI voice generation", imageTool: "AI image generation", videoTool: "Manual editing" },
];

export const mockPublishingRecords: PublishingRecord[] = [
  { id: "pub_001", episodeId: "ep_005", episodeTitle: "The Empty Chair", publicId: "nar_20261002_0005", platform: "TikTok", caption: "The chair was empty for twenty years. Today, a letter explains why. #shortstory", hashtags: ["#shortstory", "#myanmar", "#narrativ"], scheduledDate: "2026-09-27 18:00", state: "Published Record", thumbnailGradient: grad(0), formatReady: true, thumbnailReady: true, subtitleReady: true, platformUrl: "https://tiktok.com/@narrativforge/video/mock_001", notes: "Posted manually. Good engagement." },
  { id: "pub_002", episodeId: "ep_005", episodeTitle: "The Empty Chair", publicId: "nar_20261002_0005", platform: "YouTube Shorts", caption: "A letter about an empty chair reaches the person who was supposed to sit in it.", hashtags: ["#shorts", "#story", "#myanmar"], scheduledDate: "2026-09-27 19:00", state: "Published Record", thumbnailGradient: grad(1), formatReady: true, thumbnailReady: true, subtitleReady: true, platformUrl: "https://youtube.com/shorts/mock_001", notes: "Posted manually." },
  { id: "pub_003", episodeId: "ep_002", episodeTitle: "Three Minutes Before Sunrise", publicId: "nar_20261002_0002", platform: "TikTok", caption: "The last light in the city has a secret. #shortstory", hashtags: ["#shortstory", "#mystery", "#narrativ"], scheduledDate: "2026-10-03 18:00", state: "Prepared", thumbnailGradient: grad(2), formatReady: true, thumbnailReady: true, subtitleReady: true, platformUrl: "", notes: "" },
  { id: "pub_004", episodeId: "ep_002", episodeTitle: "Three Minutes Before Sunrise", publicId: "nar_20261002_0002", platform: "Instagram Reels", caption: "Before the sun rises, the last streetlight shares its memory.", hashtags: ["#reels", "#story", "#yangon"], scheduledDate: "2026-10-03 19:00", state: "Scheduled Metadata Ready", thumbnailGradient: grad(3), formatReady: true, thumbnailReady: true, subtitleReady: true, platformUrl: "", notes: "" },
  { id: "pub_005", episodeId: "ep_007", episodeTitle: "Rain on a Stranger's Shoulder", publicId: "nar_20261002_0007", platform: "TikTok", caption: "Twelve blocks. One umbrella. No words.", hashtags: ["#shortstory", "#rain", "#narrativ"], scheduledDate: "—", state: "Not Ready", thumbnailGradient: grad(4), formatReady: true, thumbnailReady: true, subtitleReady: false, platformUrl: "", notes: "Waiting for approval." },
];

export const mockAnalytics: AnalyticsRecord[] = [
  { id: "an_001", episodeId: "ep_005", episodeTitle: "The Empty Chair", platform: "TikTok", views: 42000, watchTime: "2:01", completionRate: 74, shares: 310, saves: 180, comments: 45, linkClicks: 92, recordedDate: "2026-09-28" },
  { id: "an_002", episodeId: "ep_005", episodeTitle: "The Empty Chair", platform: "YouTube Shorts", views: 28000, watchTime: "2:15", completionRate: 71, shares: 180, saves: 120, comments: 28, linkClicks: 51, recordedDate: "2026-09-28" },
  { id: "an_003", episodeId: "log_002", episodeTitle: "The Last Bus Home", platform: "TikTok", views: 58000, watchTime: "2:25", completionRate: 81, shares: 520, saves: 340, comments: 67, linkClicks: 110, recordedDate: "2026-09-20" },
  { id: "an_004", episodeId: "log_004", episodeTitle: "The Clock That Stopped at 3:17", platform: "TikTok", views: 67000, watchTime: "2:33", completionRate: 83, shares: 680, saves: 420, comments: 89, linkClicks: 145, recordedDate: "2026-09-26" },
];

export const mockActivity: ActivityEvent[] = [
  { id: "act_001", timestamp: "2026-10-02 08:45:12", actor: "Min Min Ei", role: "Owner", action: "Episode approved", target: "Three Minutes Before Sunrise (nar_20261002_0002)", previousState: "Needs Approval", newState: "Approved", requestId: "req_8a3f2b" },
  { id: "act_002", timestamp: "2026-10-02 08:30:05", actor: "Min Min Ei", role: "Owner", action: "Subtitle issue resolved", target: "The Message That Arrived Tomorrow (nar_20261002_0001)", previousState: "Critical", newState: "Needs Review", requestId: "req_7c2e1a" },
  { id: "act_003", timestamp: "2026-10-01 16:22:40", actor: "May Thiri", role: "Reviewer", action: "Review requested", target: "Rain on a Stranger's Shoulder (nar_20261002_0007)", previousState: "Subtitle Review", newState: "Needs Approval", requestId: "req_6b1d0c" },
  { id: "act_004", timestamp: "2026-10-01 14:15:33", actor: "Ko Htet", role: "Creator", action: "Asset uploaded", target: "ep004_video_v1.mp4", previousState: "—", newState: "Draft", requestId: "req_5a0c9d" },
  { id: "act_005", timestamp: "2026-10-01 09:30:18", actor: "System", role: "Worker", action: "Processing started", target: "Video Render — A Photograph with No Face", previousState: "Queued", newState: "Processing", requestId: "req_490f8e" },
  { id: "act_006", timestamp: "2026-09-30 18:10:22", actor: "Min Min Ei", role: "Owner", action: "Script updated", target: "The Message That Arrived Tomorrow — v3.2", previousState: "v3.1", newState: "v3.2", requestId: "req_380e7f" },
  { id: "act_007", timestamp: "2026-09-30 14:22:00", actor: "System", role: "Worker", action: "Transcript generated", target: "The Message That Arrived Tomorrow", previousState: "—", newState: "Completed", requestId: "req_27d6e0" },
  { id: "act_008", timestamp: "2026-09-29 16:40:15", actor: "System", role: "Worker", action: "Thumbnail generated", target: "Three Minutes Before Sunrise", previousState: "—", newState: "Completed", requestId: "req_16c5d1" },
  { id: "act_009", timestamp: "2026-09-26 11:02:45", actor: "Min Min Ei", role: "Owner", action: "Drive export completed", target: "The Empty Chair (nar_20261002_0005)", previousState: "Exporting", newState: "Exported", requestId: "req_05b4c2" },
  { id: "act_010", timestamp: "2026-09-25 15:20:30", actor: "Ko Htet", role: "Creator", action: "Manual log added", target: "The Clock That Stopped at 3:17", previousState: "—", newState: "Logged", requestId: "req_94a3b3" },
];

export const mockCharacters: Character[] = [
  { id: "ch_001", seriesId: "ser_001", name: "May", role: "Protagonist", personality: "Curious, quiet, observant. Tends to follow mysteries wherever they lead.", visualTraits: "Long dark hair, simple clothes, amber pendant from grandmother.", voiceNotes: "Soft, measured narration. Slight melancholy.", continuityWarnings: "Always wears the amber pendant. Never shown smiling broadly.", gradient: grad(0) },
  { id: "ch_002", seriesId: "ser_001", name: "The Tea Shop Owner", role: "Supporting", personality: "Warm, watchful, speaks in proverbs.", visualTraits: "Older man, apron, tea stains on hands.", voiceNotes: "Deep, gravelly, comforting.", continuityWarnings: "Tea shop setting must always show the same window.", gradient: grad(1) },
  { id: "ch_003", seriesId: "ser_002", name: "Thinzar", role: "Protagonist", personality: "Independent, analytical, slightly paranoid after the first transmission.", visualTraits: "Short hair, headphones around neck, radio operator uniform.", voiceNotes: "Clear, precise, sometimes whispers.", continuityWarnings: "Always has headphones visible. Never seen without the radio.", gradient: grad(2) },
];

export const mockVisualStyles: VisualStyle[] = [
  { id: "vs_001", seriesId: "ser_001", palette: ["#1a1a2e", "#16213e", "#0f3460", "#e94560", "#f5f5dc"], lighting: "Low-key, warm amber practicals, moonlight blue", cameraStyle: "Static with slow push-ins. Handheld for emotional peaks.", imageStyle: "Photorealistic, film grain, shallow depth of field", aspectRatio: "9:16 vertical (1080×1920)", promptGuidance: "Cinematic, moody, warm amber practical light, film grain, shallow DOF, 9:16", referenceFrames: ["attic_moonlight_ref.png", "tea_shop_warm_ref.png", "rooftop_golden_ref.png"] },
  { id: "vs_002", seriesId: "ser_002", palette: ["#0a0a0f", "#1a1a2e", "#16213e", "#4BC7E8", "#F7F5FA"], lighting: "Cool blue night, radio glow, occasional warm practical", cameraStyle: "Locked-off shots, slow pans, focus pulls", imageStyle: "Slightly desaturated, cool tones, subtle glow on light sources", aspectRatio: "9:16 vertical (1080×1920)", promptGuidance: "Cool blue night, radio equipment glow, desaturated, cinematic, 9:16", referenceFrames: ["radio_station_night_ref.png", "city_rooftop_blue_ref.png"] },
];

export const mockNotifications: Notification[] = [
  { id: "n_001", type: "warning", title: "Critical subtitle issue", message: "2 critical issues found in 'The Message That Arrived Tomorrow'", time: "10 min ago", episodeId: "ep_001", read: false },
  { id: "n_002", type: "success", title: "Processing completed", message: "Transcription for 'The Message That Arrived Tomorrow' is ready", time: "2h ago", episodeId: "ep_001", read: false },
  { id: "n_003", type: "info", title: "Review requested", message: "May Thiri requested review for 'Rain on a Stranger's Shoulder'", time: "5h ago", episodeId: "ep_007", read: true },
  { id: "n_004", type: "error", title: "Job failed", message: "Timestamp Alignment failed for 'The Voice That Called from Yesterday'", time: "1d ago", episodeId: "ep_006", read: true },
  { id: "n_005", type: "success", title: "Export completed", message: "'The Empty Chair' has been exported to mock Drive", time: "2d ago", episodeId: "ep_005", read: true },
];
